config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit , :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end

  authenticate :user do
    resources :product_models, only: [:index, :show, :new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user
  enum status: {
    pending: 0,

    delivered: 5,

    canceled: 7
  }
  validates :code, :estimated_delivery_date, presence: true
  validate :estimated_delivery_date_is_future

  before_validation :generate_code

  private
  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def estimated_delivery_date_is_future
    if self.estimated_delivery_date.present? && self.estimated_delivery_date <= Date.today
      self.errors.add :estimated_delivery_date, " deve ser futura."
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  validates :name, :sku, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, presence: true
  validates :state, length: {is: 2}
  validates :registration_number, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  def description
    "#{name} - #{email}"
  end
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord

  validates :name, :code, :city, :area, :address, :cep, :description, presence: true
  validates :code, length: { is: 3 }
  validates :code, uniqueness: true

  def full_description
    "#{code} - #{name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @warehouses = Warehouse.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user, only: [:show, :edit, :update, :delivered, :canceled]

  def new
    @order = Order.new
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def create
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
    @order = Order.new(order_params)
    @order.user = current_user
    @order.save!
    redirect_to @order, notice: 'Pedido registrado com suceso.'
  end

  def show ; end

  def index
    @orders = current_user.orders
  end

  def search
    @code = params["query"]
    @orders = Order.where("code LIKE ?", "%#{@code}%")
  end

  def edit
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def update
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)

    @order.update(order_params)
    redirect_to @order, notice: 'Pedido atualizado com sucesso!'
  end

  def delivered
    @order.delivered!
    redirect_to @order, notice: "Pedido Entregue!"
  end

  def canceled
    @order.canceled!
    redirect_to @order, notice: "Pedido Cancelado!"
  end

  private
  def check_user
    @order = Order.find(params[:id])
    if @order.user != current_user
      return redirect_to root_path, notice: "Você não tem permissão para acessar essa página!"
    end
  end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  # before_action :authenticate_user!, only: [:index]
  def index
    @product_models = ProductModel.all
  end

  def new
    @supplier = Supplier.all
    @product_model = ProductModel.new
  end

  def create
    @product_model = ProductModel.new(product_model_params)
    if @product_model.save
      redirect_to @product_model, notice: "Modelo de Produto cadastrado com sucesso!"
    else
      @supplier = Supplier.all
      flash.now[:notice] = 'Não foi possível cadastrar o modelo de produto!'
      render 'new'
    end

  end

  def show
    @product_model = ProductModel.find params[:id]
  end

  private
  def product_model_params
    params.require(:product_model).permit(:name, :weight, :width, :height, :depth, :sku, :supplier_id)
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update]

  def index
    @suppliers = Supplier.all
  end

  def show ; end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save()
      redirect_to suppliers_path, notice: "Fornecedor cadastrado com sucesso!"
    else
      flash.now[:notice] = "Fornecedor não cadastrado!"
      render 'new'
    end
  end

  def edit ; end

  def update
    if @supplier.update(supplier_params)
      redirect_to supplier_path(@supplier.id), notice: "Fornecedor atualizado com sucesso!"
    else
      flash.now[:notice] = "Não foi possível atualizar o fornecedor!"
      render 'edit'
    end

  end


  private
  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email)
  end

end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: [:show, :edit, :update, :destroy]

  def show ; end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)
    if @warehouse.save()
      redirect_to root_path, notice: "Galpão cadastrado com sucesso!"
    else
      flash.now[:notice] = "Galpão não cadastrado!"
      render 'new'
    end
  end

  def edit ; end

  def update
    if @warehouse.update(warehouse_params)
      redirect_to warehouse_path(@warehouse.id), notice: "Galpão atualizado com sucesso!"
    else
      flash.now[:notice] = "Não foi possível atualizar o galpão!"
      render 'edit'
    end
  end

  def destroy
    @warehouse.destroy
    redirect_to root_path, notice: 'Galpão removido com sucesso'
  end

  private
  def set_warehouse
    @warehouse = Warehouse.find(params[:id])
  end

  def warehouse_params
    params.require(:warehouse).permit(:name, :code, :city, :area, :address, :cep, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div>
    <%= link_to  "Cadastrar Galpão", new_warehouse_path %>
</div>

<section id="warehouses">
  <h2>Galpões</h2>
    <% @warehouses.each do |w| %>
      <div>
        <h3><%= link_to w.name, w%></h3>
        <dl>
          <dt>Código:</dt>
          <dd><%= w.code%></dd>
          <dt>Cidade:</dt>
          <dd><%= w.city%></dd>
          <dt>Área:</dt>
          <dd> <%= w.area%> m²</dd>
        </dl>
      </div>
    <% end %>

    <% if @warehouses.empty? %>
      <p>Não existem galpões cadastrados</p>
    <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%= link_to root_path do %>
        <h1>Galpões & Estoque</h1>
      <% end %>
      <nav>
        <%= link_to 'Fornecedores', suppliers_path %>
        <%= link_to 'Modelos de Produtos', product_models_path %>
        <%= link_to 'Registrar Pedido', new_order_path %>
        <%= link_to 'Meus Pedidos', orders_path %>


        <% if user_signed_in? %>
          <%= form_with url: search_orders_path, method: :get do |f|%>
            <%= f.label :query, 'Buscar Pedido' %>
            <%= f.text_field :query %>
            <%= f.submit 'Buscar' %>
          <% end %>
          Olá, <%= current_user.name %>!
          <%= current_user.description %>
          <%= button_to 'Sair', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Entrar', new_user_session_path %>
        <% end %>

      </nav>
    </header>
    <main>
      <div>
       <%= notice %>
       <%= alert %>
      </div>
      <%= yield %>
    </main>

  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with model: @order do |f|%>
  <div>
    <%= f.label :warehouse_id, 'Galpão' %>
    <%= f.collection_select(:warehouse_id, @warehouses, :id, :full_description) %>
  </div>
  <div>
    <%= f.label :supplier_id, 'Fornecedor' %>
    <%= f.collection_select(:supplier_id, @suppliers, :id, :corporate_name) %>
  </div>
  <div>
    <%= f.label :estimated_delivery_date, 'Data Prevista de Entrega' %>
    <%= f.date_field :estimated_delivery_date %>
  </div>

  <%= f.submit 'Gravar' %>

<% end %>

app/views/orders/_order.html.erb
<dl>
  <dt>Código:</dt>
  <dd><%= link_to order.code, order %></dd>
  <dt>Galpão Destino:</dt>
  <dd><%= order.warehouse.full_description %></dd>
  <dt>Fornecedor:</dt>
  <dd><%= order.supplier.corporate_name %></dd>
  <dt>Usuário Responsável:</dt>
  <dd><%= order.user.description %></dd>
  <dt>Data Prevista de Entrega:</dt>
  <dd><%= I18n.localize order.estimated_delivery_date %></dd>
  <dt><%= Order.human_attribute_name(:status) %></dt>
  <dd><%= t(order.status) %></dd>
</dl>

app/views/orders/edit.html.erb
<h1>Editar Pedido @order.code</h1>



<%= render 'form' %>

app/views/orders/index.html.erb
<h1>Meus Pedidos</h1>

<% if @orders.present? %>
  <p><%= @orders.count %> <%= Order.model_name.human(count: @orders.count).downcase %> <%= t(:found, count: @orders.count) %></p>
  <% @orders.each do |order| %>
    <%= render order %>
  <% end %>
<%# else %>
<% end %>

app/views/orders/new.html.erb
<h1>Registrar Pedido</h1>


<%= render 'form' %>

app/views/orders/search.html.erb
<h1>Resultados da Busca por: <%= @code %></h1>


<% if @orders.present? %>
  <p><%= @orders.count %> <%= Order.model_name.human(count: @orders.count).downcase %> <%= t(:found, count: @orders.count) %></p>
  <dl>
    <% @orders.each do |order| %>
      <dt>Código:</dt>
      <dd><%= order.code %></dd>
      <dt>Galpão Destino:</dt>
      <dd><%= order.warehouse.full_description %></dd>
      <dt>Fornecedor:</dt>
      <dd><%= order.supplier.corporate_name %></dd>
      <dt>Usuário Responsável:</dt>
      <dd><%= order.user.description %></dd>
      <dt>Data Prevista de Entrega:</dt>
      <dd><%= I18n.localize order.estimated_delivery_date %></dd>
    <% end %>
</dl>
<%# else %>
<% end %>

app/views/orders/show.html.erb
<h1>Detalhes do Pedido</h1>
<h2>Pedido <%= @order.code %></h2>
<dl>
  <dt>Galpão Destino:</dt>
  <dd><%= @order.warehouse.full_description %></dd>
  <dt>Fornecedor:</dt>
  <dd><%= @order.supplier.corporate_name %></dd>
  <dt>Usuário Responsável:</dt>
  <dd><%= @order.user.description %></dd>
  <dt>Data Prevista de Entrega:</dt>
  <dd><%= I18n.localize @order.estimated_delivery_date %></dd>
  <dt><%= Order.human_attribute_name(:status) %>:</dt>
  <dd><%= t(@order.status) %></dd>
</dl>

<%= button_to 'Marcar como ENTREGUE', delivered_order_path(@order) %>
<%= button_to 'Marcar como CANCELADO', canceled_order_path(@order) %>

<%= link_to 'Editar', edit_order_path(@order) %>

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>

<%= link_to 'Cadastrar Novo', new_product_model_path %>

<% if @product_models.any? %>
  <% @product_models.each do |pm| %>
    <div>
      <h2><%= pm.name %></h2>
      <dl>
        <dt> SKU </dt>
        <dd><%= pm.sku %> </dd>
        <dt> Fornecedor: </dt>
        <dd><%= pm.supplier.brand_name %></dd>
      </dl>
    </div>
  <% end %>
<% else %>
  <p>Não existem modelos de produtos cadastrados!</p>
<% end %>

app/views/product_models/new.html.erb
<h1>Cadastrar Novo Modelo de Produto</h1>

<%= form_with model: @product_model do |f|%>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>

  <div>
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>

  <div>
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>

  <div>
    <%= f.label :depth %>
    <%= f.number_field :depth %>
  </div>

  <div>
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>

  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @supplier , :id, :brand_name %>
  </div>

  <%= f.submit %>


<% end %>

app/views/product_models/show.html.erb
<h1><%= @product_model.name %></h1>
<dl>
  <dt>Fornecedor:</dt>
  <dd><%= @product_model.supplier.brand_name %></dd>
  <dt>SKU:</dt>
  <dd><%= @product_model.sku %></dd>
  <dt>Peso:</dt>
  <dd><%= @product_model.weight %>g</dd>
  <dt>Dimensão:</dt>
  <dd><%= @product_model.width %>cm x <%= @product_model.height %>cm x <%= @product_model.depth %>cm</dd>
</dl>

app/views/suppliers/_form.html.erb
<%= form_with model: @supplier do |f|%>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>
  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/suppliers/edit.html.erb
<% if @supplier.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @supplier.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
<% end %>

<h1>Editar Fornecedor</h1>
<%= render 'form' %>

app/views/suppliers/index.html.erb
<h2>Fornecedores</h2>

<div>
  <%= link_to  "Cadastrar Fornecedor", new_supplier_path %>
</div>
<br>
<div>
  <section id="suppliers">
    <% if @suppliers.any? %>
      <table>
        <thead>
          <tr>
            <th>Nome</th>
            <th>Localização</th>
          </tr>
        </thead>
        <tbody>
          <% @suppliers.each do |s| %>
          <tr>
            <td><%= link_to s.brand_name, s %></td>
            <td><%= s.city %> - <%= s.state %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    <% else %>
      <p>Não existem fornecedores cadastrados!</p>
    <% end %>
  </section>
</div>

app/views/suppliers/new.html.erb
<h1>Novo Fornecedor:</h1>


<% if @supplier.errors.any? %>

  <p>Verifique os erros abaixo:</p>
  <ul>

    <% @supplier.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>

<% end %>



<%= render 'form' %>

app/views/suppliers/show.html.erb
<h2><%= Supplier.model_name.human %>: <%= @supplier.brand_name %></h2>
<%= @supplier.corporate_name %>

<div>
  <strong><%= Supplier.human_attribute_name(:registration_number) %>: </strong> <%= @supplier.registration_number %><br>
  <strong>Endereço: </strong><%= @supplier.full_address %><br>
  <strong>Cidade: </strong><%= @supplier.city %> - <%= @supplier.state %><br>
  <strong>Email: </strong><%= @supplier.email %>
</div>

<%= link_to "Voltar", suppliers_path %>
<%= link_to "Editar", edit_supplier_path(@supplier) %>

app/views/warehouses/_form.html.erb
<%= form_with model: @warehouse do |f|%>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>
  <div>
    <%= f.label :area %>
    <%= f.number_field :area %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<h1>Editar Galpão</h1>
<%= render 'form' %>

app/views/warehouses/new.html.erb
<h1>Novo Galpão:</h1>

<% if (@warehouse.errors.any?) %>
<p>Verifique os erros abaixo:</p>
<ul>

  <% @warehouse.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>

  <% end %>

</ul>
<% end %>


<%= render 'form' %>

app/views/warehouses/show.html.erb
<h1> Galpão <%= @warehouse.code %> </h1>
  <%= @warehouse.description %>
<div>
  <strong>Nome:</strong> <%= @warehouse.name %><br>
  <strong>Cidade:</strong> <%= @warehouse.city %><br>
  <strong>Área:</strong> <%= @warehouse.area %> m²<br>
  <strong>Endereço:</strong> <%= @warehouse.address %> - <strong>CEP:  </strong><%= @warehouse.cep %><br>
</div>

<%= link_to "Editar", edit_warehouse_path(@warehouse) %>
<%= button_to "Remover", warehouse_path(@warehouse.id), method: :delete %>
<%= link_to "Voltar", root_path %>